# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yPFiTp1Hsj3TUSQ3PKBKF6bWvZS3H7Jb
"""

"""
    Stage: Development-01
    @author: Almustafa alshekfeh 119202008
    @author: kaan gökdere 119202038
    
    Development-02:
    @author: Selin Yılmaz, 119203057
    @author: Mohammed Nael, 120202003
    @author: Süleyman Mehmet Güneş, 119200077

"""

import tkinter as tk
testloginusername = 'test_username'
testloginpassword = 'test_pass'


class LoginWindow:
    # constructor
    def __init__(self):
        self.window = tk.Tk()

        self._initializeGUI()
        self._addGUIElementsToFrame()

        # start the GUI frame
        self.window.mainloop()


    """
        Initialize GUI elements. If it is necessary, you can add
        more elements.

        ! PLEASE RENAME THE OBJECTS ACCORDING TO THEIR PURPOSES !
        ! YOU CAN ADD MORE ELEMENTS IF IT IS NECESSARY !
    """
    def _initializeGUI(self):
        self.lbl01 = tk.Label(text="Label-01")
        self.lbl02 = tk.Label(text="Label-02")

        self.txt01 = tk.Entry()
        self.txt02 = tk.Entry()

        self.btn01 = tk.Button(text="Btn-01")
        self.btn02 = tk.Button(text="Btn-02")

        self.btn01.bind("<Button-1>", self.handle_click)
        self.btn02.bind("<Button-1>", self.handle_click)


    """
        Add GUI elements to the layout of the frame. If it is necessary,
        you can add more elements.
    """
    def _addGUIElementsToFrame(self):
        self.lbl01.grid(row=0, column=0, padx=10, pady=5)
        self.txt01.grid(row=0, column=1, padx=10, pady=5)

        self.lbl02.grid(row=1, column=0, padx=10, pady=5)
        self.txt02.grid(row=1, column=1, padx=10, pady=5)

        self.btn01.grid(row=2, column=0, padx=10, pady=5)
        self.btn02.grid(row=2, column=1, padx=10, pady=5)


    """
        Action listener for the buttons. If "event.widget" is from
        one of the buttons, apply the related operation.

        :param event: action event for detecting which button is clicked
    """

    def handle_click(self, event):
        window2 = tk.Tk()
        window2.mainloop()
        pass

    def handle_click2(self, event):
        window3 = tk.Tk()
        window3.mainloop()
        pass



# main method for testing the application
if __name__ == "__main__":
    LoginWindow()